---
- hosts: all
  become: yes

  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:
  - name: Deploy k3s cluster
    shell: curl -sfL https://get.k3s.io | sh -

  - name: Adding 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' in the .bashrc
    lineinfile: dest=/root/.bashrc line='export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' insertafter='EOF' regexp='export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' state=present

  - name: Source the bashrc file
    shell: '. /root/.bashrc'

  - name: Ensure pyhelm and dependencies are installed.
    pip:
      name:
        - pyhelm
        - grpcio
      state: present

  - name: Install php App Guestbook
    shell: k3s kubectl apply -f https://raw.githubusercontent.com/flyer8/exness/master/guestbook/guestbook-all-in-one.yaml

  # - name: Clone repo exness
  #   shell: |
  #     rm -rf ~/exness || true
  #     git clone https://github.com/flyer8/exness.git ~/exness

  - git:
      repo: 'https://github.com/flyer8/exness.git'
      dest: ~/exness
      clone: yes
      update: yes

  - name: Install Helm chart Nginx
    shell: helm upgrade web ~/exness/chart.nginx --install

  - name: Test conection
    shell: helm test web
    register: result

  - debug:
      var: result
      verbosity: 2
