---
- hosts: all
  become: yes
  tasks:

  - name: Deploy k3s cluster
    shell: curl -sfL https://get.k3s.io | sh - && export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

  - name: Ensure pyhelm and dependencies are installed.
    pip:
      name:
        - pyhelm
        - grpcio
      state: present

  - name: Install PHP App Guestbook
    shell: kubectl apply -f https://raw.githubusercontent.com/flyer8/exness/master/guestbook/guestbook-all-in-one.yaml

  # - name: Clone repo exness
  #   shell: |
  #     rm -rf ~/exness || true
  #     git clone https://github.com/flyer8/exness.git ~/exness

  - git:
      repo: 'https://github.com/flyer8/exness.git'
      dest: ~/exness
      clone: yes
      update: yes

  - name: Install Helm chart Nginx
    shell: helm upgrade web ~/exness/chart.nginx --install


  # - name: Add Helm Stable repo
  #   shell: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

  # - name: Install helm chart from a git repo specifying path
  #   helm:
  #     host: localhost
  #     chart:
  #       source:
  #         type: git
  #         location: https://github.com/flyer8/exness.git
  #         path: chart.nginx
  #     state: present
  #     name: nginx
  #     namespace: default
